### ISSUE TITLE
command :Timedot opens today's timedot entries in a lower split

### ISSUE THREAD

**Issue by linuxcaffe** [steshaw/timedot-vim#3]
could just be tail of my.timedot file, open in a lower split, cursor at the bottom, ready to edit.
If the last date in the file is earlier than today, then create today's YYYY/MM/DD /n on a new line.

would probably require something like 
let g:timedot_file=path/to/my.timedot
let g:timedot_window_location=bottom
let g:timedot_window_height=8
 .vimrc settings. 

This might be beyond the scope of your plugin, but I thought I'd toss it out there ;-)

**Comment by steshaw** [comment]
Yeah, this is beyond the scope of my plugin and my Vimscript knowledge 😅. I was using Timedot via Emacs for a while but because my go-to editor is Neovim, I put this together to help with syntax highlighting. These days, I use Emacs for all my Org editing which includes when my Org contains some embedded Timedot. I'm even experimenting with giving up detailed time recording 🙊.

Perhaps you'd like to fork the project and take over maintainership?
